# teleop_twist_joy configuration.
# https://index.ros.org/p/teleop_twist_joy

# Configuration for Logitech gamepad.
teleop_twist_joy_node:
  ros__parameters:
    axis_linear: # Joystick axis used to update the linear x value.
      x: 1
    scale_linear:
      x: 5.0

    axis_angular: # Joystick axis used to update the twist roll value.
      roll: 3
    scale_angular:
      roll: 5.0

    # configure the dead man's switch.
    require_enable_button: false
    enable_button: 5 # Trigger
