version: "3.3"

services:
  app:
    image: stepit:latest
    container_name: stepit
    build: . # Build an image with a Dockerfile located in the current directory.
    volumes:
      # Set the env variable STEPIT_PATH to the root of your project.
      - ${STEPIT_PATH}:/home/developer/repo/stepit
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    # Use this when you have a corresponding device attached.
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    hostname: stepit
    entrypoint: /home/developer/entrypoint.sh
    stdin_open: true # Equivalent to "docker run -i".
    tty: true # Equivalent to "docker run -t".
    env_file:
      - container.env
