version: "3.3"

services:
  app:
    image: stepit:latest
    container_name: stepit
    privileged: true # This is required to access the hardware.
    build: . # Build an image with a Dockerfile located in the current directory.
    volumes:
      # Set the env variable STEPIT_PATH to the root of your project.
      - ${STEPIT_PATH}:/home/developer/repo/stepit
      # Allow the user to run graphical programs from within the docker container.
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    hostname: stepit
    tty: true # Equivalent to "docker run -t".
    stdin_open: true # Equivalent to "docker run -i".
