# Logitech gamepad
teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Forward/Back
      x: 1
    scale_linear:
      x: 1.0
    scale_linear_turbo:
      x: 1.5

    axis_angular:  # Twist
      yaw: 2
    scale_angular:
      yaw: 0.5

    enable_button: 5  # Trigger
