name: ROS Lint

on: [push, pull_request]

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, lint_cmake]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@0.7
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: jazzy
          linter: ${{ matrix.linter }}
          package-name: cobs_serial
            freezer_controller
            freezer_description
            freezer_driver
            freezer_msgs
            robot_bringup
            robot_description
            stepit_driver
            stepit_hardware_tests
            robot_teleop

  ament_lint_121:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        linter: [cpplint]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@0.7
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: jazzy
          linter: cpplint
          arguments: "--linelength=121 --filter=-whitespace/newline"
          package-name: cobs_serial
            freezer_controller
            freezer_description
            freezer_driver
            freezer_msgs
            robot_bringup
            robot_description
            stepit_driver
            stepit_hardware_tests
            robot_teleop
